// simplified specialist diseases CRUD
import { NextRequest, NextResponse } from "next/server";
import { getAuthenticatedUser, getSupabaseConfig, supabaseRequest } from "../../../../lib/agronomic/case";
import type { UserRole } from "../../../../lib/auth";
import { requireUuid } from "../../../../lib/server/uuid";
type Profile = { id: string; role: UserRole; status?: "active" | "inactive" | null };
const clean=(v:unknown)=> typeof v==='string'&&v.trim()?v.trim():null;
const emptyToNull=(v:unknown)=> typeof v==='string'&&v.trim()===''?null:v;
function getToken(request: NextRequest) { return request.headers.get("authorization")?.replace(/^Bearer\s+/i, "") || null; }
function adminCfg(){ const c=getSupabaseConfig(); const key=process.env.SUPABASE_SERVICE_ROLE_KEY; if(!key) throw new Error('SUPABASE_SERVICE_ROLE_KEY ausente'); return {...c, anonKey:key}; }
async function ensureSpecialist(token: string) { const user = await getAuthenticatedUser(token); const rows = await supabaseRequest<Profile[]>(`/rest/v1/profiles?id=eq.${encodeURIComponent(user.id)}&select=id,role,status&limit=1`, { method: "GET" }, token); const p=rows[0]; if(!p||!["admin","specialist"].includes(p.role)||(p.status??"active")!=="active") return {error:NextResponse.json({error:"Acesso negado."},{status:403})}; return {user}; }
export async function GET(request: NextRequest){ try{const token=getToken(request); if(!token) return NextResponse.json({error:'Faça login.'},{status:401}); const auth=await ensureSpecialist(token); if(auth.error) return auth.error; const cfg=adminCfg(); const rows=await supabaseRequest('/rest/v1/acompanhamento_diseases?select=*&order=common_name.asc',{method:'GET'},cfg.anonKey,cfg); return NextResponse.json({diseases:rows}); }catch(e){ return NextResponse.json({error:e instanceof Error?e.message:'erro'},{status:500}); }}
export async function POST(request: NextRequest){ try{const token=getToken(request); if(!token) return NextResponse.json({error:'Faça login.'},{status:401}); const auth=await ensureSpecialist(token); if(auth.error) return auth.error; const b=await request.json(); const common_name=clean(b.common_name); if(!common_name) return NextResponse.json({error:'Nome comum obrigatório.'},{status:400}); const { id: _ignoredId, created_by: _ignoredCreatedBy, updated_by: _ignoredUpdatedBy, ...rest } = b ?? {}; const payload = Object.fromEntries(Object.entries(rest).map(([k,v])=>[k,emptyToNull(v)])); const cfg=adminCfg(); const rows=await supabaseRequest('/rest/v1/acompanhamento_diseases?select=*',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({...payload,common_name,is_active:b.is_active!==false,created_by:auth.user.id,updated_by:auth.user.id})},cfg.anonKey,cfg); return NextResponse.json({disease:Array.isArray(rows)?rows[0]:rows}); }catch(e){ return NextResponse.json({error:e instanceof Error?e.message:'erro'},{status:500}); }}
export async function PATCH(request: NextRequest){ try{const token=getToken(request); if(!token) return NextResponse.json({error:'Faça login.'},{status:401}); const auth=await ensureSpecialist(token); if(auth.error) return auth.error; const b=await request.json(); const id=requireUuid(b?.id); if(!id) return NextResponse.json({error:'ID inválido.'},{status:400}); const { id: _ignoredId, created_by: _ignoredCreatedBy, ...rest } = b ?? {}; const payload = Object.fromEntries(Object.entries(rest).map(([k,v])=>[k,emptyToNull(v)])); const cfg=adminCfg(); const rows=await supabaseRequest(`/rest/v1/acompanhamento_diseases?id=eq.${encodeURIComponent(id)}&select=*`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({...payload,updated_by:auth.user.id})},cfg.anonKey,cfg); return NextResponse.json({disease:Array.isArray(rows)?rows[0]:rows}); }catch(e){ return NextResponse.json({error:e instanceof Error?e.message:'erro'},{status:500}); }}
export async function DELETE(request: NextRequest){ try{const token=getToken(request); if(!token) return NextResponse.json({error:'Faça login.'},{status:401}); const auth=await ensureSpecialist(token); if(auth.error) return auth.error; const id=requireUuid(new URL(request.url).searchParams.get('id')); if(!id) return NextResponse.json({error:'ID obrigatório.'},{status:400}); const cfg=adminCfg(); await supabaseRequest(`/rest/v1/acompanhamento_diseases?id=eq.${encodeURIComponent(id)}`,{method:'DELETE'},cfg.anonKey,cfg); return NextResponse.json({ok:true}); }catch(e){ return NextResponse.json({error:e instanceof Error?e.message:'erro'},{status:500}); }}
