import Link from "next/link";

const benefits = ["Maior valor agregado e diferenciação de mercado","Produção mais sustentável e melhoria da fertilidade do solo","Redução gradual da dependência de insumos externos","Conexão com consumidores que buscam alimentos saudáveis","Mais canais de comercialização: feiras, cestas, mercados locais e programas institucionais"];
const challenges = ["Diagnóstico completo da propriedade","Planejamento da transição com metas e cronograma","Ajustes no manejo do solo e nutrição","Controle alternativo de pragas e doenças","Escolha adequada de culturas e cultivares","Registros e documentação do processo","Viabilidade econômica e acompanhamento técnico"];
const timeline = ["Diagnóstico da propriedade","Levantamento de culturas, solo, histórico de manejo e principais problemas","Definição dos objetivos do produtor","Planejamento da transição","Ajustes no manejo do solo e da adubação","Implantação de práticas agroecológicas","Monitoramento de pragas, doenças e produtividade","Organização de registros","Acompanhamento técnico e melhoria contínua"];

export default function Page() {
  return <div className="mx-auto max-w-6xl px-6 py-14 space-y-6">
    <section className="rounded-3xl border border-[#123F2A]/15 bg-gradient-to-br from-white via-[#F8FCF7] to-[#EDF6ED] p-8 md:p-11">
      <h1 className="text-4xl font-bold text-[#123F2A] md:text-5xl">Converta sua propriedade para agricultura orgânica com orientação especializada</h1>
      <p className="mt-4 text-lg text-slate-700">Planejamento técnico, diagnóstico da propriedade e acompanhamento para produtores que desejam iniciar ou aprimorar a produção orgânica.</p>
      <p className="mt-4 text-slate-700">A agricultura orgânica é uma oportunidade para produtores que buscam agregar valor à produção, acessar novos mercados, melhorar a saúde do solo e construir sistemas produtivos mais sustentáveis. A transição, porém, exige planejamento, conhecimento técnico e acompanhamento para reduzir riscos e evitar erros comuns.</p>
    </section>
    <section className="rounded-3xl border bg-white p-7"><h2 className="text-2xl font-bold text-[#123F2A]">O que é agricultura orgânica</h2><p className="mt-3 text-slate-700">É um sistema de produção baseado no equilíbrio do solo, biodiversidade e manejo sustentável, com menor dependência de insumos químicos sintéticos. Valoriza a saúde do solo, da água, das plantas e do consumidor, com planejamento e rastreabilidade.</p></section>
    <section className="grid gap-6 md:grid-cols-2"><article className="rounded-3xl border bg-white p-7"><h2 className="text-2xl font-bold text-[#123F2A]">Por que converter para orgânico</h2><ul className="mt-4 space-y-2 text-slate-700">{benefits.map((b)=><li key={b}>• {b}</li>)}</ul></article><article className="rounded-3xl border bg-white p-7"><h2 className="text-2xl font-bold text-[#123F2A]">Desafios da conversão</h2><ul className="mt-4 space-y-2 text-slate-700">{challenges.map((c)=><li key={c}>• {c}</li>)}</ul></article></section>
    <section className="rounded-3xl border bg-white p-7"><h2 className="text-2xl font-bold text-[#123F2A]">Como a especialista pode ajudar</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 text-slate-700">{["Diagnóstico inicial da propriedade","Avaliação do sistema produtivo atual","Planejamento da transição para orgânico","Orientação sobre manejo do solo","Sugestão de práticas sustentáveis","Manejo de hortaliças orgânicas","Controle alternativo de pragas e doenças","Produção de mudas","Planejamento de cultivos","Apoio para organização de informações técnicas","Visita técnica para avaliação presencial"].map((i)=><div key={i} className="rounded-2xl border bg-[#F8FCF7] p-4">{i}</div>)}</div></section>
    <section className="rounded-3xl border bg-white p-7"><h2 className="text-2xl font-bold text-[#123F2A]">Etapas sugeridas da conversão orgânica</h2><ol className="mt-4 space-y-2 text-slate-700">{timeline.map((step,i)=><li key={step}><span className="font-semibold text-[#2E7D32]">{i+1}.</span> {step}</li>)}</ol></section>
    <section className="rounded-3xl border bg-white p-7"><h2 className="text-2xl font-bold text-[#123F2A]">Agricultura orgânica para hortaliças</h2><p className="mt-3 text-slate-700">A consultoria contempla produção orgânica de hortaliças, tomateiro e melancia com foco em produção de mudas, tratos culturais, nutrição, fitossanidade, caldas alternativas e manejo integrado de pragas e doenças.</p></section>
    <section className="rounded-3xl border border-[#2E7D32]/20 bg-[#123F2A] p-7 text-white"><h2 className="text-2xl font-bold">Pronto para avaliar a conversão da sua propriedade?</h2><p className="mt-2 text-white/80">Solicite uma análise inicial e receba direcionamento técnico adequado ao seu contexto produtivo.</p><Link href="/contact?requestType=conversao_propriedade_organica" className="mt-5 inline-block rounded-full bg-[#A7C957] px-7 py-3 font-semibold text-[#123F2A]">Agendar visita pelo formulário de contato</Link></section>
  </div>;
}
