"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import SectionTitle from "../../../components/SectionTitle";
import { getStoredSupabaseAccessToken } from "../../../lib/supabaseAuth";

type Disease={id:string;common_name:string;scientific_name?:string|null;disease_type?:string|null;symptoms?:string|null;severity_level?:string|null;management_recommendations?:string|null;is_active:boolean};
const empty={common_name:"",scientific_name:"",disease_type:"",symptoms:"",severity_level:"",management_recommendations:"",is_active:true,id:""};
export default function Page(){const [items,setItems]=useState<Disease[]>([]);const [form,setForm]=useState<any>(empty);const [q,setQ]=useState("");const [msg,setMsg]=useState<string|null>(null);const [err,setErr]=useState<string|null>(null);
const token=()=>getStoredSupabaseAccessToken();
async function load(){const t=token(); if(!t) return; const r=await fetch('/api/specialist/diseases',{headers:{Authorization:`Bearer ${t}`}}); const p=await r.json(); if(r.ok) setItems(p.diseases??[]); else setErr(p.error||'Erro');}
useEffect(()=>{load();},[]);
async function submit(e:FormEvent){e.preventDefault();const t=token(); if(!t) return; const method=form.id?'PATCH':'POST'; const r=await fetch('/api/specialist/diseases',{method,headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`},body:JSON.stringify(form)}); const p=await r.json(); if(!r.ok){setErr(p.error||'Erro');return;} setMsg('Doença salva com sucesso.'); setForm(empty); load();}
const visible=items.filter(x=>`${x.common_name} ${x.scientific_name??''}`.toLowerCase().includes(q.toLowerCase()));
return <section className="mx-auto max-w-7xl px-6 py-12"><Link href="/configuracoes">← Configurações</Link><SectionTitle title="Cadastro de Doenças" subtitle="Gestão técnica de doenças para monitoramento fitossanitário." />{err&&<p>{err}</p>}{msg&&<p>{msg}</p>}<form onSubmit={submit} className="grid gap-3 md:grid-cols-2">{Object.entries({common_name:'Nome comum *',scientific_name:'Nome científico',disease_type:'Tipo',symptoms:'Sintomas principais',severity_level:'Nível de severidade',management_recommendations:'Manejo'}).map(([k,l])=><label key={k}>{l}<textarea required={k==='common_name'} className="w-full border p-2" value={form[k]??''} onChange={e=>setForm((c:any)=>({...c,[k]:e.target.value}))}/></label>)}<label className="md:col-span-2"><input type="checkbox" checked={form.is_active} onChange={e=>setForm((c:any)=>({...c,is_active:e.target.checked}))}/> Ativa</label><button className="rounded bg-green-700 p-2 text-white">Salvar</button></form><input className="mt-4 w-full border p-2" placeholder="Buscar doença" value={q} onChange={e=>setQ(e.target.value)} /><div className="mt-4 space-y-2">{visible.length===0?<p>Nenhuma doença cadastrada.</p>:visible.map(d=><article key={d.id} className="rounded border p-3"><strong>{d.common_name}</strong><p>{d.scientific_name}</p><div className="flex gap-3"><button onClick={()=>setForm(d)}>Editar</button><button onClick={async()=>{const t=token(); if(!t) return; await fetch(`/api/specialist/diseases?id=${d.id}`,{method:'DELETE',headers:{Authorization:`Bearer ${t}`}}); load();}}>Excluir</button></div></article>)}</div></section>}
