"use client";
import { useEffect, useState, type FormEvent } from "react";
import SectionTitle from "../../../components/SectionTitle";
import { getStoredSupabaseAccessToken } from "../../../lib/supabaseAuth";

type KnowledgeCategory = "protocolo"|"artigo"|"aula"|"recomendacao"|"faq"|"caso_pratico"|"manejo"|"solo"|"pragas"|"doencas";
type KnowledgeMaterial = {id:string;title:string|null;category:KnowledgeCategory|null;crop:string|null;content:string|null;file_url:string|null;active:boolean|null;created_at:string|null;};
const categories = [{value:"protocolo",label:"Protocolo"},{value:"artigo",label:"Artigo"},{value:"aula",label:"Aula"},{value:"recomendacao",label:"Recomendação"},{value:"faq",label:"FAQ"},{value:"caso_pratico",label:"Caso prático"},{value:"manejo",label:"Manejo"},{value:"solo",label:"Solo"},{value:"pragas",label:"Pragas"},{value:"doencas",label:"Doenças"}] as const;
const emptyForm={title:"",category:"protocolo" as KnowledgeCategory,crop:"",content:"",file_url:"",active:true};
function parse(r:Response){return r.json().catch(()=>null).then(p=>{if(!r.ok) throw new Error(p?.error||"Falha"); return p;});}
export default function Page(){
const [materials,setMaterials]=useState<KnowledgeMaterial[]>([]); const [form,setForm]=useState(emptyForm); const [editingId,setEditingId]=useState<string|null>(null); const [msg,setMsg]=useState<string|null>(null); const [err,setErr]=useState<string|null>(null); const [loading,setLoading]=useState(true); const [submitting,setSubmitting]=useState(false); const [selectedFile,setSelectedFile]=useState<File|null>(null);
const token=getStoredSupabaseAccessToken();
async function load(){ if(!token){setErr("Faça login para acessar.");setLoading(false);return;} setLoading(true); try{const p=await parse(await fetch('/api/specialist/knowledge',{headers:{Authorization:`Bearer ${token}`}})); setMaterials(p.materials||[]);}catch(e){setErr(e instanceof Error?e.message:'Erro');} finally{setLoading(false);} }
useEffect(()=>{load();},[]);
async function onSubmit(e:FormEvent){e.preventDefault(); if(!token) return; setSubmitting(true); setErr(null); setMsg(null); try{await parse(await fetch('/api/specialist/knowledge',{method:editingId?'PATCH':'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({id:editingId,...form})})); setMsg(editingId?"Material atualizado com sucesso.":"Material cadastrado com sucesso."); setForm(emptyForm); setEditingId(null); await load();}catch(ex){setErr(ex instanceof Error?ex.message:'Erro');} finally{setSubmitting(false);} }
async function onUpload(){if(!selectedFile||!token) return; const fd=new FormData(); fd.append('file',selectedFile); try{const p=await parse(await fetch('/api/specialist/knowledge/upload',{method:'POST',headers:{Authorization:`Bearer ${token}`},body:fd})); setForm(c=>({...c,file_url:p.fileUrl})); setMsg('Arquivo enviado com sucesso.');}catch(ex){setErr(ex instanceof Error?ex.message:'Erro upload');}}
async function onDelete(id:string){ if(!token||!confirm('Deseja realmente excluir este material?')) return; try{await parse(await fetch('/api/specialist/knowledge',{method:'DELETE',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({id})})); setMsg('Material excluído com sucesso.'); await load();}catch(ex){setErr(ex instanceof Error?ex.message:'Erro excluir');}}
return <section className="mx-auto max-w-7xl px-6 py-14 md:py-20"><SectionTitle title="Base de Conhecimento" subtitle="Gerencie os materiais técnicos da equipe especialista." />
<div className="mt-6 rounded-3xl border border-leaf-100 bg-white p-6 shadow-soft">{err&&<p className="text-red-700 text-sm">{err}</p>}{msg&&<p className="text-emerald-700 text-sm">{msg}</p>}
<form onSubmit={onSubmit} className="mt-4 grid gap-4 md:grid-cols-2"><input required value={form.title} onChange={e=>setForm(c=>({...c,title:e.target.value}))} placeholder="Título" className="rounded-2xl border px-4 py-3 text-sm"/><select value={form.category} onChange={e=>setForm(c=>({...c,category:e.target.value as KnowledgeCategory}))} className="rounded-2xl border px-4 py-3 text-sm">{categories.map(c=><option key={c.value} value={c.value}>{c.label}</option>)}</select><input value={form.crop} onChange={e=>setForm(c=>({...c,crop:e.target.value}))} placeholder="Tipo/material/cultura" className="rounded-2xl border px-4 py-3 text-sm"/><input type="url" value={form.file_url} onChange={e=>setForm(c=>({...c,file_url:e.target.value}))} placeholder="Link do arquivo" className="rounded-2xl border px-4 py-3 text-sm"/><textarea value={form.content} onChange={e=>setForm(c=>({...c,content:e.target.value}))} placeholder="Descrição/conteúdo" className="rounded-2xl border px-4 py-3 text-sm md:col-span-2" rows={4}/><div><input type="file" onChange={e=>setSelectedFile(e.target.files?.[0]||null)} className="text-sm"/><button type="button" onClick={onUpload} className="ml-2 rounded-full border px-4 py-2 text-xs">Enviar arquivo</button></div><label className="text-sm"><input type="checkbox" checked={form.active} onChange={e=>setForm(c=>({...c,active:e.target.checked}))}/> Ativo</label><button disabled={submitting} className="rounded-full bg-leaf-600 px-5 py-3 text-white text-sm">{submitting?'Salvando...':editingId?'Atualizar':'Cadastrar'}</button></form></div>
<div className="mt-6 space-y-3">{loading?<div>Carregando...</div>:materials.length===0?<div className="rounded-2xl border bg-white p-5 text-sm text-slate-600">Nenhum material cadastrado ainda.</div>:materials.map(m=><article key={m.id} className="rounded-2xl border bg-white p-5"><div className="flex justify-between gap-3"><div><h3 className="font-semibold">{m.title||'Sem título'}</h3><p className="text-xs text-slate-500">{m.category||'Sem categoria'} • {m.crop||'Não informado'} • {m.created_at?new Date(m.created_at).toLocaleString('pt-BR'):'Data não informada'} • {m.active?'Ativo':'Inativo'}</p><p className="text-sm mt-2 whitespace-pre-line">{m.content||'Sem descrição'}</p>{m.file_url&&<a className="text-sm text-leaf-700 underline" href={m.file_url} target="_blank" rel="noreferrer">Abrir arquivo/link</a>}</div><div className="flex gap-2"><button onClick={()=>{setEditingId(m.id);setForm({title:m.title||'',category:(m.category||'protocolo'),crop:m.crop||'',content:m.content||'',file_url:m.file_url||'',active:!!m.active});}} className="rounded-full border px-3 py-1 text-xs">Editar</button><button onClick={()=>onDelete(m.id)} className="rounded-full border px-3 py-1 text-xs">Excluir</button></div></div></article>)}</div></section>;
}
